const divbloxPackageControllerBase = require('divbloxjs/dx-core-modules/package-controller-base');
const DivbloxBase = require("divbloxjs/divblox");

/*
This package controller was generated by the divbloxjs package generator.
*/

class ElectricityMeter extends divbloxPackageControllerBase {
    /**
     * A basic constructor that can be overridden
     * @param {DivbloxBase} dxInstance An instance of divbloxjs to allow for access to the app configuration
     * @param {string} packageName The name given to this package
     */
    constructor(dxInstance = null, packageName = 'electricity-meter') {
        super(dxInstance, packageName);
        // TODO: Override as required
    }
    // TODO: Add package specific functionality below
}

module.exports = ElectricityMeter;